import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JFileChooser;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS
 */
public class PenghitungKataFrame extends javax.swing.JFrame {

    
    /**
     * Creates new form PenghitungKataFrame
     */
    public PenghitungKataFrame() {
        initComponents();
        // Menambahkan DocumentListener untuk menghitung otomatis saat teks berubah
             textAreaInput.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) { hitung(); }
            @Override
            public void removeUpdate(DocumentEvent e) { hitung(); }
            @Override
            public void changedUpdate(DocumentEvent e) { hitung(); }
        });
    }

    // Metode hitung untuk menghitung jumlah kata, karakter, dan kalimat
    private void hitung() {
        String teks = textAreaInput.getText();

    // Menghitung jumlah kata
    int jumlahKata = teks.trim().isEmpty() ? 0 : teks.trim().split("\\s+").length;

    // Menghitung jumlah karakter (tanpa spasi)
    int jumlahKarakter = teks.replaceAll("\\s", "").length();

    // Menghitung jumlah kalimat (menggunakan tanda titik, tanda seru, dan tanda tanya)
    int jumlahKalimat = teks.split("[.!?]").length;

    // Menghitung jumlah paragraf (misalnya paragraf dipisahkan oleh dua newline)
    int jumlahParagraf = teks.split("\\n\\s*\\n").length; // Memisahkan paragraf berdasarkan dua newline

    // Menampilkan hasil
    labelJumlahKata.setText("Jumlah Kata: " + jumlahKata);
    labelJumlahKarakter.setText("Jumlah Karakter: " + jumlahKarakter);
    labelJumlahKalimat.setText("Jumlah Kalimat: " + jumlahKalimat);
    labelJumlahParagraf.setText("Jumlah Paragraf: " + jumlahParagraf);
    }
// Fungsi untuk mencari kata dalam teks
    private void cariKata() {
    String teks = textAreaInput.getText().toLowerCase(); // Ambil teks dan ubah menjadi huruf kecil
    String kataDicari = textFieldCariKata.getText().toLowerCase(); // Ambil kata yang ingin dicari dan ubah menjadi huruf kecil

    // Mengecek apakah kata yang dicari kosong
    if (kataDicari.isEmpty()) {
        labelHasilPencarian.setText("Masukkan kata untuk mencari.");
        return;
    }

    // Menghitung jumlah kemunculan kata dalam teks
    int count = 0;
    int index = 0;
    while ((index = teks.indexOf(kataDicari, index)) != -1) {
        count++;
        index += kataDicari.length(); // Melanjutkan pencarian setelah kata yang ditemukan
    }

    // Menampilkan hasil pencarian
    if (count > 0) {
        labelHasilPencarian.setText("Kata '" + kataDicari + "' ditemukan sebanyak " + count + " kali.");
    } else {
        labelHasilPencarian.setText("Kata '" + kataDicari + "' tidak ditemukan.");
    }
  
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelInputTeks = new javax.swing.JLabel();
        jScrollPaneTextArea = new javax.swing.JScrollPane();
        textAreaInput = new javax.swing.JTextArea();
        buttonHitung = new javax.swing.JButton();
        buttonKeluar = new javax.swing.JButton();
        labelJumlahKata = new javax.swing.JLabel();
        labelJumlahKarakter = new javax.swing.JLabel();
        labelJumlahKalimat = new javax.swing.JLabel();
        labelJumlahParagraf = new javax.swing.JLabel();
        textFieldCariKata = new javax.swing.JTextField();
        labelHasilPencarian = new javax.swing.JLabel();
        buttonCari = new javax.swing.JButton();
        buttonSimpan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Aplikasi Penghitung Kata ");

        labelInputTeks.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        labelInputTeks.setText("Masukkan Teks");

        jScrollPaneTextArea.setBackground(new java.awt.Color(255, 255, 255));

        textAreaInput.setColumns(20);
        textAreaInput.setRows(5);
        jScrollPaneTextArea.setViewportView(textAreaInput);

        buttonHitung.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        buttonHitung.setText("Hitung");
        buttonHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHitungActionPerformed(evt);
            }
        });

        buttonKeluar.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        buttonKeluar.setText("Keluar");
        buttonKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKeluarActionPerformed(evt);
            }
        });

        labelJumlahKata.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        labelJumlahKata.setText("Jumlah Kata");

        labelJumlahKarakter.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        labelJumlahKarakter.setText("Jumlah Karakter");

        labelJumlahKalimat.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        labelJumlahKalimat.setText("Jumlah Kalimat");

        labelJumlahParagraf.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        labelJumlahParagraf.setText("Menampilkan Jumlah Paragraf");

        textFieldCariKata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldCariKataActionPerformed(evt);
            }
        });

        labelHasilPencarian.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        labelHasilPencarian.setText("Tampilkan Hasil Pencarian");

        buttonCari.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        buttonCari.setText("Cari");
        buttonCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCariActionPerformed(evt);
            }
        });

        buttonSimpan.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        buttonSimpan.setText("Simpan");
        buttonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSimpanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelInputTeks)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPaneTextArea)
                        .addGap(36, 36, 36))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelJumlahParagraf)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(buttonSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buttonHitung, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(buttonKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelHasilPencarian)
                            .addComponent(labelJumlahKalimat)
                            .addComponent(labelJumlahKarakter)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelJumlahKata)
                                .addGap(174, 174, 174)
                                .addComponent(textFieldCariKata, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(buttonCari, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(20, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(162, 162, 162))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(labelInputTeks))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPaneTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(labelJumlahKata)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addComponent(labelJumlahKarakter)
                        .addGap(34, 34, 34)
                        .addComponent(labelJumlahKalimat)
                        .addGap(26, 26, 26)
                        .addComponent(labelJumlahParagraf)
                        .addGap(27, 27, 27)
                        .addComponent(labelHasilPencarian)
                        .addGap(0, 93, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textFieldCariKata, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonCari, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonHitung, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHitungActionPerformed
    hitung(); // Panggil metode hitung saat tombol ditekan
    }//GEN-LAST:event_buttonHitungActionPerformed

    private void buttonKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKeluarActionPerformed
       System.exit(0); // Menutup aplikasi
    }//GEN-LAST:event_buttonKeluarActionPerformed

    private void textFieldCariKataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldCariKataActionPerformed
       
    }//GEN-LAST:event_textFieldCariKataActionPerformed

    private void buttonCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCariActionPerformed
       cariKata(); // Panggil fungsi cari kata saat tombol "Cari" ditekan
    }//GEN-LAST:event_buttonCariActionPerformed

    private void buttonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSimpanActionPerformed
          // Menampilkan dialog untuk memilih lokasi penyimpanan
    JFileChooser fileChooser = new JFileChooser();
    fileChooser.setDialogTitle("Simpan File");
    int userSelection = fileChooser.showSaveDialog(this);
    
    if (userSelection == JFileChooser.APPROVE_OPTION) {
        File fileToSave = fileChooser.getSelectedFile();
        try (BufferedWriter writer = new BufferedWriter(new FileWriter(fileToSave))) {
            // Menulis teks yang dimasukkan ke file
            writer.write("Teks Input:\n");
            writer.write(textAreaInput.getText());
            writer.write("\n\n");

            // Menulis hasil perhitungan ke file
            writer.write("Hasil Perhitungan:\n");
            writer.write(labelJumlahKata.getText() + "\n");
            writer.write(labelJumlahKarakter.getText() + "\n");
            writer.write(labelJumlahKalimat.getText() + "\n");
            writer.write(labelJumlahParagraf.getText() + "\n");

            labelHasilPencarian.setText("Teks dan hasil telah disimpan di " + fileToSave.getAbsolutePath());
        } catch (IOException e) {
            labelHasilPencarian.setText("Terjadi kesalahan saat menyimpan file.");
            e.printStackTrace();
        }
    }
    }//GEN-LAST:event_buttonSimpanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PenghitungKataFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PenghitungKataFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PenghitungKataFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PenghitungKataFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PenghitungKataFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCari;
    private javax.swing.JButton buttonHitung;
    private javax.swing.JButton buttonKeluar;
    private javax.swing.JButton buttonSimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPaneTextArea;
    private javax.swing.JLabel labelHasilPencarian;
    private javax.swing.JLabel labelInputTeks;
    private javax.swing.JLabel labelJumlahKalimat;
    private javax.swing.JLabel labelJumlahKarakter;
    private javax.swing.JLabel labelJumlahKata;
    private javax.swing.JLabel labelJumlahParagraf;
    private javax.swing.JTextArea textAreaInput;
    private javax.swing.JTextField textFieldCariKata;
    // End of variables declaration//GEN-END:variables
}
